name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "30 14 * * *"

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.5

  windows-yamatanooroti:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, windows-2022 ]
        ruby: [ 3.2, mingw ]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install Windows Terminal
        run: |
          choco install microsoft-windows-terminal -y --no-progress
      - name: check wt.exe existence
        run: |
          where wt.exe || dir>NUL
      - name: rake test
        run: |
          set TESTOPTS=-v
          call rake test
