name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "30 14 * * *"

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 2.5

  windows-yamatanooroti:
    name: >-
      ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2022 ]
        ruby: [ 3.2, mingw ]
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: install Windows Terminal
        run: |
          #choco install microsoft-windows-terminal --version 1.21.2361 -y --no-progress
          mkdir tmp
          mkdir tmp\zip
          curl -O --output-dir tmp/zip -L https://github.com/microsoft/terminal/releases/download/v1.21.2361.0/Microsoft.WindowsTerminal_1.21.2361.0_x64.zip
          c:\windows\system32\tar --help
          c:\windows\system32\tar xzvf tmp/zip/Microsoft.WindowsTerminal_1.21.2361.0_x64.zip -C tmp
          dir tmp
          dir tmp\zip
          dir "tmp\terminal-1.21.2361.0"
      - name: check wt.exe existence
        run: |
          where wt.exe || dir>NUL
      - name: rake test
        run: |
          set TESTOPTS=-v
          call rake test
